### ISSUE TITLE
Improve the use of the input file config.yml

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#94]
Now if we want to test different scenarii in the config file we have to do it this way (for instance to test the influcence of aggregation_weighting method for random and stratified:

```
experiment_name: weight_test
n_repeats: 10
scenario_params_list:
 - nodes_counts: 3
   amounts_per_node: [0.4, 0.3, 0.3] 
   samples_split_option: 'Random'
   aggregation_weighting: 'data_volume'
 - nodes_counts: 3
   amounts_per_node: [0.4, 0.3, 0.3] 
   samples_split_option: 'Random'
   aggregation_weighting: 'uniform'
 - nodes_counts: 3
   amounts_per_node: [0.4, 0.3, 0.3] 
   samples_split_option: 'Stratified'
   aggregation_weighting: 'data_volume'
 - nodes_counts: 3
   amounts_per_node: [0.4, 0.3, 0.3] 
   samples_split_option: 'Random'
   aggregation_weighting: 'uniform'

```

An easier way to produce the same result would be to use lists:

```
experiment_name: weight_test
n_repeats: 10
scenario_params_list:
 - nodes_counts: 3
   amounts_per_node: [0.4, 0.3, 0.3] 
   samples_split_option: ['Random', 'Stratified']
   aggregation_weighting: ['data_volume', 'uniform']
```
The goal is that the 2 config files generate the same 4 scenerarii.
